version: "3"

services:
  iss_tracker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: iss_tracker:1.0
    container_name: flask-iss-tracker-app
    volumes:
      - ./test:/app/test
    ports:
      - "5000:5000"
    command: ["python", "iss_tracker.py"]