version: "3"

services:
	iss_tracker:
		build:
			context: ./
			dockerfile: ./Dockerfile
		image: iss_tracker:1.0
		volumes:
			- ./test:/app/test
		user: "5000:5000"
		command: python iss_tracker.py